package ru.andrew.mainserver.audit.entity;

public enum AuditEventType {
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,

    PIN_CREATED,
    PIN_USED,
    PIN_REVOKED,
    PIN_EXPIRED,

    SESSION_STARTED,
    SESSION_EXPIRED,
    SESSION_LOGGED_OUT,
    SESSION_TERMINATED,

    CARD_BOUND,
    CARD_BLOCKED,

    BALANCE_DEPOSITED,
    BALANCE_TRANSFERRED,
    BALANCE_ADJUSTED,

    ADMIN_LOGIN_SUCCESS,
    ADMIN_LOGIN_FAILED,
    PLAYER_LOGIN_SUCCESS,
    BALANCE_WITHDRAWN, BALANCE_REVERSED, PLAYER_LOGIN_FAILED
}