package ru.andrew.mainserver.gateway.marketplace;

public enum MarketplaceCommandType {
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    CHANGE_PRODUCT_STATUS,
    ADJUST_STOCK,
    LIST_PRODUCTS,
    GET_PRODUCT,
    RESERVE_ORDER,
    CONFIRM_ORDER,
    CANCEL_ORDER,
    LIST_ORDERS,
    LIST_MY_ORDERS,
    GET_ORDER,
    MASS_PRICE_OP,
    LIST_SCENARIOS,
    CREATE_SCENARIO,
    UPDATE_SCENARIO,
    DELETE_SCENARIO,
    APPLY_SCENARIO,
    SCHEDULE_SCENARIO,
    LIST_SCHEDULES,
    CANCEL_SCHEDULE,
    TRIGGER_SCENARIO_NOW
}
